Iter9
Arcadian-Sky/musthave-metrics pull request #10
Opened 2024-04-01 14:42 UTC by Arcadian-Sky

2024-04-01 21:45 UTC, Arcadian-Sky commented
не удается победить один из тестов, непонятно что не так

2024-04-02 14:00 UTC, arttet requested changes

2024-04-02 14:00 UTC, arttet commented on internal/server/middleware/middleware.go
> +func ContentTypeSet(expectedContentType string) Middleware {
It would be better if you remove it

2024-04-02 14:00 UTC, arttet commented on internal/server/storage/configs.go
> +type Config struct {
CHANGE REQUEST: it should be in another package

2024-04-05 15:15 UTC, arttet approved these changes

2024-04-05 15:15 UTC, arttet commented on .github/dependabot.yml
> +version: 2
https://gist.github.com/magnetikonline/6f215db058e327905bce66c37f92426c

2024-04-05 15:15 UTC, arttet commented on cmd/agent/main.go
> +		panic("Panic error in flags parsing")
SUGGESTION: please don't panic here.

2024-04-05 15:15 UTC, arttet commented on internal/agent/flags/flags.go
> +	config := Config{
https://refactoring.guru/design-patterns/builder/go/example

2024-04-09 19:24 UTC, merged