Iter23
Arcadian-Sky/musthave-metrics pull request #29
Opened 2024-07-28 15:16 UTC by Arcadian-Sky

2024-07-30 11:00 UTC, arttet requested changes
Please recover autotests
![image](https://github.com/user-attachments/assets/f3a02da3-44f1-47d1-b580-1534fdb8c62d)

2024-07-30 20:57 UTC, Arcadian-Sky commented
yml updated

2024-07-31 10:04 UTC, arttet approved these changes

2024-07-31 10:04 UTC, arttet commented on internal/server/caretaker/caretaker.go
> +//go:build !coverage
It looks like a hack.

2024-08-02 21:34 UTC, merged